### PR TITLE
Dev html

### PR DESCRIPTION
**Pull request by faisalakb**
in this milestone ♻️ 

- set up linters 👍 
- set professional readme 👍 
- add index html file and CSS file 👍 
- add gitignore file 👍 
- set up test.md to be ignored 👍 
- this is a new pull request that was opened following my last code reviewers word link : [here](https://github.com/faisalakb/Hello-world/pull/2)

### CODE REVIEW

**Review by jasonfelice — CHANGES_REQUESTED** [review]
Hi @faisalakb, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
- [ ] Before requesting the next review, please make sure all the linter checks are passing. Check out [this resource](https://stackoverflow.com/questions/66626814/github-action-error-process-completed-with-exit-code-1) to fix the linter error. 😸 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by faisalakb** [comment]
@jasonfelice hope you are doing good. Can you guide me on the above build error, I tried a number of times but could not find the proper guidelines. Because it's all set on my local repo.

**Comment by faisalakb** [comment]
Please check my PR. Updated Linters problem.

**Review by binhussen — APPROVED** [review]
Hi @faisalakb , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
