### PR TITLE
Hello world Microverse Project Pull Request

### PR DESCRIPTION
**Pull request by faisalakb**
In this PR
- Created a html file that contains `h1`
- Created a styles.css file that include text color

### CODE REVIEW

**Review by aamirkhan2478 — CHANGES_REQUESTED** [review]
Hi @faisalakb , 



Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Good Effort
✔️ Your design is good.
✔️ All linters are checked
✔️ Good commit history

## Required Changes ♻️

- [ ] Please add Microverse provided [README](https://github.com/microverseinc/readme-template) file and customize it as per your project requirements.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by faisalakb** [comment]
Hi @aamirkhan2478 
In this PR, I changed the required README files instruction according to Microverse said format

**Comment by aamirkhan2478** [comment]
> Hi @aamirkhan2478 In this PR, I changed the required README files instruction according to Microverse said format

Okay send for review again :+1:

**Review by aamirkhan2478 — APPROVED** [review]
Hi @faisalakb , 

GIF

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ You used GitHub flow correctly
✅ No linter error
✅ Good commit messages
✅ Good descriptive PR

## Optional suggestions

[OPTIONAL] Please fix your MIT link this is optional but recommended.
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
